import os
from datetime import datetime

from flask import current_app

from extensions import celery
from models import (
    User,
    CompanyProfile,
    StudentProfile,
    PlacementDrive,
    Application,
)


@celery.task
def generate_monthly_report():

    now = datetime.now()

    month = now.month
    year = now.year

    # Total Counts
    total_students = StudentProfile.query.count()
    total_companies = CompanyProfile.query.count()
    total_drives = PlacementDrive.query.count()
    total_applications = Application.query.count()

    # Monthly Drives
    monthly_drives = PlacementDrive.query.filter(
        PlacementDrive.created_at >= datetime(year, month, 1)
    ).count()

    # Monthly Applications
    monthly_applications = Application.query.filter(
        Application.applied_at >= datetime(year, month, 1)
    ).count()

    # Shortlisted Students
    shortlisted = Application.query.filter_by(
        status="shortlisted"
    ).count()

    # Rejected Students
    rejected = Application.query.filter_by(
        status="rejected"
    ).count()

    # Report directory
    report_dir = os.path.join(
        current_app.root_path,
        "reports"
    )

    os.makedirs(
        report_dir,
        exist_ok=True
    )

    filename = (
        f"placement_report_{year}_{month:02d}.html"
    )

    file_path = os.path.join(
        report_dir,
        filename
    )

    month_name = now.strftime("%B")

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">

        <title>
            PlaceHub Monthly Placement Report
        </title>

        <style>
            body {{
                font-family: Arial, sans-serif;
                background: #f5f5f5;
                padding: 40px;
            }}

            .container {{
                max-width: 900px;
                margin: auto;
                background: white;
                padding: 30px;
                border-radius: 10px;
            }}

            h1 {{
                text-align: center;
            }}

            .subtitle {{
                text-align: center;
                color: #666;
                margin-bottom: 30px;
            }}

            table {{
                width: 100%;
                border-collapse: collapse;
            }}

            th,
            td {{
                padding: 15px;
                border: 1px solid #ddd;
                text-align: left;
            }}

            th {{
                background: #f2f2f2;
            }}

            .footer {{
                margin-top: 30px;
                text-align: center;
                color: #777;
                font-size: 14px;
            }}
        </style>
    </head>

    <body>

        <div class="container">

            <h1>
                PlaceHub Monthly Placement Report
            </h1>

            <p class="subtitle">
                {month_name} {year}
            </p>

            <table>

                <tr>
                    <th>Metric</th>
                    <th>Count</th>
                </tr>

                <tr>
                    <td>Total Students</td>
                    <td>{total_students}</td>
                </tr>

                <tr>
                    <td>Total Companies</td>
                    <td>{total_companies}</td>
                </tr>

                <tr>
                    <td>Total Placement Drives</td>
                    <td>{total_drives}</td>
                </tr>

                <tr>
                    <td>Total Applications</td>
                    <td>{total_applications}</td>
                </tr>

                <tr>
                    <td>Drives Created This Month</td>
                    <td>{monthly_drives}</td>
                </tr>

                <tr>
                    <td>Applications This Month</td>
                    <td>{monthly_applications}</td>
                </tr>

                <tr>
                    <td>Shortlisted Applications</td>
                    <td>{shortlisted}</td>
                </tr>

                <tr>
                    <td>Rejected Applications</td>
                    <td>{rejected}</td>
                </tr>

            </table>

            <p class="footer">
                Generated by PlaceHub on
                {now.strftime("%d %B %Y at %I:%M %p")}
            </p>

        </div>

    </body>
    </html>
    """

    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as file:
        file.write(html)

    return {
        "filename": filename
    }
